name: ci

on: [ push ]

env:
  server-directory: ./server/
  client-directory: ./client/

jobs:
  server-ci:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.server-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: ${{ env.server-directory }}
      - name: Security audit application code
        run: bundle exec brakeman -q -w2 --no-pager
      - name: Lint Ruby files
        run: bundle exec rubocop --format simple --parallel
      - name: Test application
        run: bundle exec rails test
  client-ci:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.client-directory }}
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: node-modules-${{ matrix.node-version }}-${{ hashFiles('./**/yarn.lock') }}
      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive
      - name: Run test
        run: yarn test
      - name: Type check
        run: yarn type-check
      - name: Linter check
        run: yarn lint
      - name: test build
        run: yarn build
